/*
014.test

note for TAS; assembly machine.s code for this test case was generated by ai for simplicity

This testcase is meant to validate basic user-mode syscalls and checks some kernel safety rejections.
Note: most sections of the testcase do not affect one another, so if you are failing, feel free to ignore other sections and zero in on the one that is failing.

Overview:
- open
- read
- write
- close
- lseek
- brk
- sched_yield
- fork
- exit

(most common reason for fail) ->
It also checks that the kernel safely rejects bad user pointers for:
- open
- write

*/

#include "libc.h"
#include <stdint.h>

#define SYS_read 0
#define SYS_write 1
#define SYS_open 2
#define SYS_close 3
#define SYS_lseek 8
#define SYS_brk 12
#define SYS_sched_yield 24
#define SYS_exit 60

#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2

static void put(const char *s)
{
    write(1, s, strlen(s));
}

static int streq_n(const char *a, const char *b, unsigned long n)
{
    for (unsigned long i = 0; i < n; i++) {
        if (a[i] != b[i]) return 0;
    }
    return 1;
}

/*
Print a specific failure marker and exit immediately.
The whole testcase is designed so that each failure message narrows
the bug down a lot.
*/
static void fail(const char *msg)
{
    put(msg);
    exit(1);
}

int main(void)
{
    /*
   Small stack buffer used for file reads.
   16 bytes is enough for the short reads in this testcase.
   */
    char buf[16];
    /* Zero it once at the start. */
    for (int i = 0; i < 16; i++)
        buf[i] = 0;

    put("*** START\n");

    /*
    open:
    Open a known file from the ramdisk image.
    The returned fd must be nonnegative.
    */
    int fd = (int)open("/hello");
    if (fd < 0)
        fail("*** FAIL open\n");
    put("*** open ok\n");

    /* lseek quick reminder for your convenience from syscall spec:
    lseek(fd, 0, SEEK_SET) means “go to byte 0”
    lseek(fd, 6, SEEK_SET) means “go to byte 6”
    lseek(fd, 0, SEEK_CUR) means “tell me where I am now”
    lseek(fd, 0, SEEK_END) means “move to the end and return that position,”
    */

    /*
    lseek with SEEK_CUR

    This is a quick sanity check that:
    - the fd is still valid
    - lseek itself works at all
    - SEEK_CUR is accepted
    */
    if (lseek(fd, 0, SEEK_CUR) < 0)
        fail("*** FAIL cur0\n");

    /* lseek with SEEK_END

       This checks:
       - SEEK_END dispatch
       - file size lookup through the open file/node
       - syscall return value propagation back to user mode

       failure meanings:
       - size neg: syscall returned an error
       - size zero: clearly wrong for this file
       - size other: likely wrong size computation, bad file contents,
         wrong fd state, or broken syscall return path
       */
    long sz = lseek(fd, 0, SEEK_END);
    if (sz < 0)
        fail("*** FAIL size neg\n");
    if (sz == 0)
        fail("*** FAIL size zero\n");
    if (sz != 13)
        fail("*** FAIL size other\n");
    put("*** size ok\n");

    /*
    rewind to start of file.
    This checks SEEK_SET and confirms we can reposition the current offset.
    */
    if (lseek(fd, 0, SEEK_SET) != 0)
        fail("*** FAIL rewind\n");
    put("*** rewind ok\n");

    /* read first 5 bytes.
        Expected data: "hello"

        This checks:
        read syscall dispatch
        copyout into a user buffer
        current file offset usage
        correct byte count return
        */
    long n = read(fd, buf, 5);
    if (n < 0)
        fail("*** FAIL read1 neg\n");
    if (n == 0)
        fail("*** FAIL read1 eof\n");
    if (n != 5)
        fail("*** FAIL read1 count\n");
    if (!streq_n(buf, "hello", 5))
        fail("*** FAIL read1 data\n");
    put("*** read1 ok\n");

    /* seek to byte offset 6.

    offset 6 should point at 'w' for hello world

    This checks that lseek both:
    updates the file offset
    returns the new offset
    */
    if (lseek(fd, 6, SEEK_SET) != 6)
        fail("*** FAIL seek6\n");
    put("*** seek6 ok\n");

    /* read next 5 bytes from offset 6.

        Expected: "world"

        This checks:
        offset tracking after lseek
        repeated reads on the same fd
        data correctness for a nonzero file offset
        */
    for (int i = 0; i < 16; i++)
        buf[i] = 0;
    n = read(fd, buf, 5);
    if (n < 0)
        fail("*** FAIL read2 neg\n");
    if (n == 0)
        fail("*** FAIL read2 eof\n");
    if (n != 5)
        fail("*** FAIL read2 count\n");
    if (!streq_n(buf, "world", 5))
        fail("*** FAIL read2 data\n");
    put("*** read2 ok\n");

    /* close

    This checks that the fd can be closed successfully.
    validates the normal close path and fd table cleanup
    */
    if (close(fd) != 0)
        fail("*** FAIL close\n");
    put("*** close ok\n");

    /* brk

    - brk(0) returns current break
    - brk(new_addr) tries to set the break
    - brk(0) again returns the updated break

    This checks:
    - current break query
    - small valid heap growth
    - return value correctness
    */
    long b0 = brk((void *)0);
    long b1 = brk((void *)(b0 + 64));
    long b2 = brk((void *)0);
    if (b1 != b0 + 64 || b2 != b0 + 64)
        fail("*** FAIL brk\n");
    put("*** brk ok\n");

    /* sched_yield

    check that the kernel accepts the syscall and returns success.
    prove the syscall path is wired up.
    */
    if (sched_yield() != 0)
        fail("*** FAIL yield\n");
    put("*** yield ok\n");

    /* invalid path pointer for open

    Address 8 is intentionally a bad user pointer. A correct kernel should NOT
    trust it and should reject it, usually by returning -1.

    This is useful for catching missing copyinstr / user-pointer validation.
    */
    if (open((const char *)8) != -1)
        fail("*** FAIL bad open\n");
    put("*** bad open rejected\n");

    /* invalid buffer pointer for write

    address 8 is intentionally invalid.
    A correct kernel should validate the user buffer before trying to read from it.

    This catches kernels that blindly dereference user memory in sys_write.
    */
    if (write(1, (const void *)8, 4) != -1)
        fail("*** FAIL bad write\n");
    put("*** bad write rejected\n");

    put("*** DONE\n");
    exit(0);
}